name: pyqt5-runtime-core20 
version: '20.04'
summary: PyQt5 runtime stack based on core20. 
description: |
  This snap is to be consumed by various PyQt5 apps which uses Qt 5.9+.
  Qt provides C++ classes and QML types for rendering GUI.
grade: stable 
confinement: strict 
base: core20


architectures:
  - build-on: amd64
    run-on: amd64

slots: 
  pyqt5-runtime:
    interface: content
    read: 
      - /
parts:
  desktop-qt5:
     source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
     source-subdir: qt
     plugin: make
     make-parameters: ["FLAVOR=qt5"]
     build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
     stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libdb5.3
      - libgdk-pixbuf2.0-0
      - locales-all
      - xdg-user-dirs
      - libglu1-mesa
      - libslang2
      - python3-pyqt5 #Dist python3 PyQt5 Binding(uses desktop-qt5 .SO's)
      - qt5-gtk-platformtheme #Platform themes plugin
      
  mpv-ppa:
     plugin: nil
     override-pull: |
       snapcraftctl pull
       apt install wget
       echo "deb http://ppa.launchpad.net/mc3man/mpv-tests/ubuntu bionic main" >>  /etc/apt/sources.list
       wget -qO - http://ktechpit.com/USS/Olivia/snapcraft/mpv.key | apt-key add -
       apt update
       
  deps:
     plugin: nil
     after: [mpv-ppa]
     stage-packages:
           - mpv # this is ppa version of mpv
           - ffmpeg # used by y2mate for merging audio video

  cleanup:
     after: 
       - desktop-qt5
     plugin: nil
     override-prime: |
       # Remove unneeded stage files to save space
       cd usr/share
       rm -rf apport bash-completion bug doc doc-base lintian man pam-configs pkgconfig upstart zsh
